### ISSUE TITLE
A Beginners' Documentation

### ISSUE THREAD

**Issue by CitoplasmaX** [PaulBone/plasma#3]
I suggest you should think on make Beginners' Documentation now. If not, it will go the same as with the main language you are using, Mercury.

**Comment by PaulBone** [comment]
I'm not sure that Plasma is "ready" yet for people to use. it lacks so many features that people would reasonably expect (modules, higher order programming, loops) and probably many things beginners would need (some syntax sugars, a standard library, etc).  I agree, there should be beginners' documentation, but I'm concerned that it would need to be rewritten multiple times as the language develops, not just added-to, since good documentation needs to be presented well with concepts shown in the right order, we might not know what the ideal order is until the language is "ready", and that this re-writing would become tedious for whoever is doing it.

If you feel like you want to give Plasma a try now, and this is holding you back, please tell us, I really want to know. Maybe there's something else I can help with such as making the reference manual clearer or answering some questions you have.

**Comment by CitoplasmaX** [comment]
I'm not a programmer. I'm just looking for a programming language to learn. When I met Mercury I was surprised, I liked Mercury but when I wanted to learn Mercury I saw that his tutorial was incomplete and, from my point of view, his reference guide was a disaster. I stayed fried reading only the first few pages. Jajajajajaja

**Comment by PaulBone** [comment]
I understand. I think Plasma is too "beta", I don't think you'd learn very quickly because most of the interesting and important things to learn about programming, Plasma can't do yet!

I'm working on Plasma very gradually; it's going to take some time. So I would say only try to use Plasma if you're a very patient person (and can wait for things to be finished) and don't mind helping out ;-) either with coding, reporting problems you find or working on documentation ;-).

**Comment by PaulBone** [comment]
I understand. I think Plasma is too "beta", I don't think you'd learn very quickly because most of the interesting and important things to learn about programming, Plasma can't do yet!

I'm working on Plasma very gradually; it's going to take some time. So I would say only try to use Plasma if you're a very patient person (and can wait for things to be finished) and don't mind helping out ;-) either with coding, reporting problems you find or working on documentation ;-).
